/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Sora"', "sans-serif"],
        body: ['"Outfit"', "sans-serif"],
        serif: ['"Crimson Pro"', "Georgia", "serif"],
        mono: ['"JetBrains Mono"', "monospace"],
        "label-sm": ["Cormorant Garamond"],
        "display-hero": ["Playfair Display"],
        "body-md": ["Be Vietnam Pro"],
        "body-lg": ["Be Vietnam Pro"],
        "headline-md": ["Playfair Display"],
        "label-caps": ["Cormorant Garamond"],
        "headline-lg": ["Playfair Display"]
      },
      colors: {
        "surface-container-highest": "#f8ddd3",
        "on-tertiary-fixed": "#360f00",
        "on-secondary-fixed-variant": "#643f00",
        "on-tertiary-fixed-variant": "#7d2d00",
        "background": "#fff8f6",
        "tertiary-container": "#c84d04",
        "error-container": "#ffdad6",
        "on-primary-container": "#fffbff",
        "surface-container-low": "#fff1ec",
        "outline-variant": "#e2bfb2",
        "on-tertiary-container": "#fffbff",
        "error": "#ba1a1a",
        "surface-variant": "#f8ddd3",
        "on-error-container": "#93000a",
        "secondary-fixed": "#ffddb6",
        "on-primary": "#ffffff",
        "surface-container": "#ffe9e2",
        "secondary": "#845400",
        "on-surface": "#261813",
        "inverse-on-surface": "#ffede7",
        "on-primary-fixed": "#360f00",
        "on-secondary-container": "#6f4600",
        "tertiary-fixed": "#ffdbcd",
        "secondary-fixed-dim": "#ffb95a",
        "surface-bright": "#fff8f6",
        "on-background": "#261813",
        "surface": "#fff8f6",
        "secondary-container": "#feb246",
        "inverse-surface": "#3d2d26",
        "surface-container-high": "#fee3d9",
        "surface-tint": "#a53c00",
        "inverse-primary": "#ffb597",
        "primary-container": "#c94c00",
        "surface-dim": "#efd5cb",
        "on-secondary-fixed": "#2a1800",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#5a4137",
        "primary-fixed-dim": "#ffb597",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "outline": "#8e7165",
        "on-primary-fixed-variant": "#7e2c00",
        "tertiary": "#a03b00",
        "tertiary-fixed-dim": "#ffb597",
        "primary": "#a13b00",
        "on-error": "#ffffff",
        "primary-fixed": "#ffdbcd",
        vermillion: {
          50: "#fff3f0",
          100: "#ffe4de",
          200: "#ffccc2",
          300: "#ffa899",
          400: "#ff7a6a",
          500: "#ff4d3a",
          600: "#e8321f",
          700: "#c42515",
          800: "#9e200f",
          900: "#7a1a0b",
        },
        ink: {
          50: "#f8fafc",
          100: "#f1f5f9",
          200: "#e2e8f0",
          300: "#94a3b8",
          400: "#64748b",
          500: "#475569",
          600: "#334155",
          700: "#1e293b",
          800: "#0f172a",
          900: "#020617",
          950: "#020617",
        },
        surface: {
          0: "#ffffff",
          50: "#f8fafc",
          100: "#f1f5f9",
          200: "#e2e8f0",
          300: "#cbd5e1",
          400: "#94a3b8",
        },
      },
      boxShadow: {
        "glow-sm": "0 0 15px -3px rgba(255,77,58,0.25)",
        "glow-md": "0 0 30px -5px rgba(255,77,58,0.35)",
        "glow-lg": "0 0 60px -10px rgba(255,77,58,0.4)",
        "inner-glow": "inset 0 1px 0 rgba(255,255,255,0.06)",
      },
      backgroundImage: {
        noise:
          "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.04'/%3E%3C/svg%3E\")",
        "grid-dark":
          "linear-gradient(rgba(255,255,255,0.025) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.025) 1px, transparent 1px)",
      },
      animation: {
        "slide-up": "slideUp 0.5s cubic-bezier(0.16,1,0.3,1) forwards",
        "slide-down": "slideDown 0.4s cubic-bezier(0.16,1,0.3,1) forwards",
        "fade-in": "fadeIn 0.4s ease forwards",
        "scale-in": "scaleIn 0.3s cubic-bezier(0.16,1,0.3,1) forwards",
        shimmer: "shimmer 1.8s infinite",
        float: "float 6s ease-in-out infinite",
        "pulse-glow": "pulseGlow 2s ease-in-out infinite",
      },
      keyframes: {
        slideUp: {
          from: { opacity: 0, transform: "translateY(24px)" },
          to: { opacity: 1, transform: "translateY(0)" },
        },
        slideDown: {
          from: { opacity: 0, transform: "translateY(-12px)" },
          to: { opacity: 1, transform: "translateY(0)" },
        },
        fadeIn: { from: { opacity: 0 }, to: { opacity: 1 } },
        scaleIn: {
          from: { opacity: 0, transform: "scale(0.95)" },
          to: { opacity: 1, transform: "scale(1)" },
        },
        shimmer: {
          from: { backgroundPosition: "-200% 0" },
          to: { backgroundPosition: "200% 0" },
        },
        float: {
          "0%,100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
        pulseGlow: {
          "0%,100%": { boxShadow: "0 0 15px -3px rgba(255,77,58,0.3)" },
          "50%": { boxShadow: "0 0 30px -3px rgba(255,77,58,0.6)" },
        },
      },
    },
  },
  plugins: [],
};
